#define ENCODERS_A_REVERSE
#define ENCODERS_B_REVERSE
#define ENCODER_RESOLUTIONS {4, 4, 2}


#define FORCE_NKRO

#define TAPPING_TERM 200
#define IGNORE_MOD_TAP_INTERRUPT
#define COMBO_TERM 35
#define COMBO_ONLY_FROM_LAYER 0
#define EXTRA_SHORT_COMBOS
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define MK_3_SPEED

#undef FP_POINTING_DEFAULT_DPI 
#define FP_POINTING_DEFAULT_DPI 1200
#define FP_POINTING_SNIPING_DPI 200