// #define COMBO_COUNT 24
#define FORCE_NKRO

#define COMBO_TERM 35
#define COMBO_ONLY_FROM_LAYER 0

#define TAPPING_TERM 200
#define IGNORE_MOD_TAP_INTERRUPT
// #define TAPPING_FORCE_HOLD

// #define PERMISSIVE_HOLD_PER_KEY
// #define PERMISSIVE_HOLD
// #define HOLD_ON_OTHER_KEY_PRESS
// #define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define LEADER_TIMEOUT 500

#define TAPPING_TOGGLE 3

