
#define RGBLED_NUM 19
#define DRIVER_LED_TOTAL RGBLED_NUM

#define MK_3_SPEED

#define FP_POINTING_DEFAULT_DPI 1000

#define FP_POINTING_SNIPING_LAYER_ENABLE
#define FP_POINTING_SNIPING_LAYER 5

#define FP_STARTUP_ANIMATION_DISABLE 1
#define FP_LAYER_LIGHTING_DISABLE 1

// #define CIRQUE_PINNACLE_TAP_ENABLE

#define RGBLIGHT_LAYERS

#define FORCE_NKRO

#define COMBO_TERM 35
#define COMBO_TERM_PER_COMBO
#define COMBO_ONLY_FROM_LAYER 0
// #define COMBO_MUST_PRESS_IN_ORDER_PER_COMBO

#define TAPPING_TERM 200
#define IGNORE_MOD_TAP_INTERRUPT
// #define TAPPING_FORCE_HOLD

// #define PERMISSIVE_HOLD_PER_KEY
// #define PERMISSIVE_HOLD
// #define HOLD_ON_OTHER_KEY_PRESS
// #define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define LEADER_TIMEOUT 500

#define TAPPING_TOGGLE 4

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
